### ISSUE TITLE
About how to get the intermediate image

### ISSUE THREAD

**Issue by lilubit** [siddiquesalman/flatnet-separable#2]
Good job!  It seems that the variable “Xout” in function “FlatNet”  is the intermediate result.  But it's 1*4*256*256.  Maybe some conversion to RGB space is needed?  Looking forward to your reply！

**Comment by siddiquesalman** [comment]
Hi, if you're using a Batchx4x500x620 input to FlatNet, then Xout will be Batchx256x256x4. We have 4 channels because we are directly working in the Bayer space. To get RGB from this 4 channel Xout, you can either throw away one of the green channels or take the average of the two green channels.

**Comment by lilubit** [comment]
Got it! Thanks a lot!
